'use client';

import { useState, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { CopyToPlatform } from '@/components/copy-to-platform';



import { DashboardLayout } from '@/components/dashboard-layout';
import { RichEditor } from '@/components/editor/rich-editor';
import { PosterGenerator } from '@/components/editor/poster-generator';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
    Wand2, Save, Send, ArrowLeft, Image, CalendarDays,
    Video, FileText, Sparkles, Check, Loader2, Clock, TrendingUp
} from 'lucide-react';
import {
    Dialog, DialogContent, DialogDescription, DialogFooter,
    DialogHeader, DialogTitle, DialogTrigger,
} from "@/components/ui/dialog"
import Link from 'next/link';
import { api } from '@/lib/api';
import { toast } from 'sonner';
import { FileUploader } from '@/components/upload/file-uploader';

// 平台选项... (不变)
const platforms = [
    { id: 'douyin', name: '抖音', icon: '🎵', color: 'bg-black' },
    { id: 'xiaohongshu', name: '小红书', icon: '📕', color: 'bg-red-500' },
    { id: 'bilibili', name: 'B站', icon: '📺', color: 'bg-blue-400' },
    { id: 'wechat', name: '公众号', icon: '💬', color: 'bg-green-500' },
];

function CreateContentForm() {
    const router = useRouter();
    const searchParams = useSearchParams();
    const editId = searchParams.get('id');
    const typeParam = searchParams.get('type');

    const [title, setTitle] = useState('');
    const [content, setContent] = useState('');
    const [selectedPlatforms, setSelectedPlatforms] = useState<string[]>(['douyin']);
    const [contentType, setContentType] = useState<'video' | 'image' | 'article'>((typeParam as any) || 'video');
    const [isGenerating, setIsGenerating] = useState(false);
    const [isSaving, setIsSaving] = useState(false);
    const [contentId, setContentId] = useState<string | null>(editId);
    const [activeTab, setActiveTab] = useState('editor');
    const [isLoading, setIsLoading] = useState(false);
    const [isPolishing, setIsPolishing] = useState(false);
    const [isLayout, setIsLayout] = useState(false);
    const [copyDialogOpen, setCopyDialogOpen] = useState(false);
    const [tags, setTags] = useState<string[]>([]);

    // Load existing draft if editing
    useEffect(() => {
        if (editId) {
            setIsLoading(true);
            api.content.get(editId).then(res => {
                if (res.success && res.data) {
                    setTitle(res.data.title || '');
                    setContent(res.data.body || '');
                    setContentType(res.data.type || 'video');
                    setSelectedPlatforms(res.data.platforms || ['douyin']);
                    setContentId(editId);
                }
            }).catch(console.error).finally(() => setIsLoading(false));
        }
    }, [editId]);

    const handlePlatformToggle = (platformId: string) => {
        // ... (不变)
        setSelectedPlatforms(prev =>
            prev.includes(platformId)
                ? prev.filter(id => id !== platformId)
                : [...prev, platformId]
        );
    };

    const handleAIGenerate = async () => {
        if (!title) {
            toast.error('请先输入标题/选题');
            return;
        }

        setIsGenerating(true);
        try {
            // Call real AI API
            const res = await api.ai.generateContent({
                topic: title,
                platform: selectedPlatforms[0] || 'douyin',
                contentType: contentType || 'video'
            });

            if (res.success && res.data) {
                // Determine content to set based on response structure
                // Assuming res.data.outline is the main content or similar
                const generatedText = res.data.outline || res.data.content || JSON.stringify(res.data, null, 2);

                // Convert simple text/markdown to HTML format for editor if needed
                // For now, simpler is better. If it's markdown, RichEditor might handle it or we wrap it in basic tags.
                let htmlContent = generatedText;
                if (!generatedText.startsWith('<')) {
                    htmlContent = `
                        <h2>📌 ${title}</h2>
                        <div class="ai-generated-content">
                            ${generatedText.replace(/\n/g, '<br/>')}
                        </div>
                        <p><strong>(Generated by SoloMedia AI)</strong></p>
                     `;
                }

                setContent(htmlContent);
                toast.success('AI生成完成');
            } else {
                toast.error(res.error || 'AI 生成失败');
            }
        } catch (error) {
            console.error('AI Generate error:', error);
            toast.error('请求AI服务出错');
        } finally {
            setIsGenerating(false);
        }
    };

    // AI Polish Handler
    const handleAIPolish = async () => {
        if (!content || content.length < 10) {
            toast.error('请先输入一些内容');
            return;
        }

        setIsPolishing(true);
        const toastId = toast.loading('AI 正在润色内容...');

        try {
            // Pass content to polish
            const res = await api.ai.polishText(content, selectedPlatforms[0] || 'douyin');

            if (res.success && res.data?.data) {
                const polishedContent = res.data.data.content;
                const quality = res.data.data.quality;

                // Keep HTML format if it was HTML, otherwise wrap
                let htmlContent = polishedContent;
                if (typeof polishedContent === 'string' && !polishedContent.startsWith('<') && !polishedContent.includes('</')) {
                    htmlContent = polishedContent.replace(/\n/g, '<br/>');
                }

                setContent(htmlContent);
                toast.dismiss(toastId);
                toast.success(`✨ AI 润色完成 (质量分: ${Math.round(quality * 100)})`);
            } else {
                toast.dismiss(toastId);
                toast.error(res.error || 'AI 润色失败');
            }
        } catch (error: any) {
            console.error('AI Polish error:', error);
            toast.dismiss(toastId);
            toast.error(error.message || 'AI 润色服务出错');
        } finally {
            setIsPolishing(false);
        }
    };

    // AI Layout Handler
    const handleAILayout = async () => {
        if (!content || content.length < 10) {
            toast.error('请先输入一些内容');
            return;
        }

        setIsLayout(true);
        const toastId = toast.loading('AI 正在优化排版...');

        try {
            const res = await api.ai.generateLayout(content, selectedPlatforms[0] || 'xiaohongshu');

            if (res.success && res.data?.data) {
                const layoutContent = res.data.data.content;

                let htmlContent = layoutContent;
                // If it looks like markdown/plain text, convert newlines to br
                if (typeof layoutContent === 'string' && !layoutContent.startsWith('<') && !layoutContent.includes('</')) {
                    htmlContent = layoutContent.replace(/\n/g, '<br/>');
                }

                setContent(htmlContent);
                toast.dismiss(toastId);
                toast.success('🎨 排版优化完成');
            } else {
                toast.dismiss(toastId);
                toast.error(res.error || 'AI 排版失败');
            }
        } catch (error: any) {
            console.error('AI Layout error:', error);
            toast.dismiss(toastId);
            toast.error('AI 排版服务出错');
        } finally {
            setIsLayout(false);
        }
    };

    const handleSave = async (showToast = true) => {
        console.log('[DEBUG] handleSave called, title state:', title, 'content length:', content.length);
        if (!title) {
            toast.error('请输入内容标题');
            return null;
        }

        setIsSaving(true);
        try {
            const data = {
                title,
                body: content,
                type: contentType,
                platforms: selectedPlatforms as any,
            };

            let res;
            if (contentId) {
                res = await api.content.update(contentId, data);
            } else {
                res = await api.content.create(data);
            }
            console.log('[DEBUG] API response:', res);

            if (res.success && res.data) {
                setContentId(res.data.id);
                if (showToast) toast.success('草稿已保存');
                return res.data.id;
            } else {
                console.log('[DEBUG] Save failed, error:', res.error);
                toast.error(res.error || '保存失败');
                return null;
            }
        } catch (error) {
            console.error('[DEBUG] Save exception:', error);
            toast.error('保存出错');
            return null;
        } finally {
            setIsSaving(false);
        }
    };

    // 打开复制发布对话框
    const handleOpenCopyDialog = async () => {
        if (!title.trim() && !content.trim()) {
            toast.error('请先填写内容');
            return;
        }
        // 先保存
        await handleSave(false);
        setCopyDialogOpen(true);
    };

    // 从内容中提取标签
    const extractTags = (text: string): string[] => {
        const matches = text.match(/#[\u4e00-\u9fa5a-zA-Z0-9]+/g) || [];
        return matches.map(t => t.replace('#', '')).slice(0, 10);
    };

    return (
        <DashboardLayout>
            <div className="space-y-6">
                {/* 顶部导航 */}
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <Link href="/content">
                            <Button variant="ghost" size="icon">
                                <ArrowLeft className="h-5 w-5" />
                            </Button>
                        </Link>
                        <div>
                            <h1 className="text-2xl font-bold">{editId ? '编辑内容' : '创建新内容'}</h1>
                            <p className="text-muted-foreground">使用AI助手快速创作优质内容</p>
                        </div>
                    </div>
                    <div className="flex gap-2">
                        <Button variant="outline" onClick={() => handleSave(true)} disabled={isSaving}>
                            {isSaving ? <Loader2 className="h-4 w-4 mr-2 animate-spin" /> : <Save className="h-4 w-4 mr-2" />}
                            {isSaving ? '保存中...' : '保存草稿'}
                        </Button>

                        <Dialog open={copyDialogOpen} onOpenChange={setCopyDialogOpen}>
                            <DialogTrigger asChild>
                                <Button
                                    className="bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-700 hover:to-indigo-700"
                                    onClick={handleOpenCopyDialog}
                                    disabled={isSaving}
                                >
                                    <Send className="h-4 w-4 mr-2" />
                                    去发布
                                </Button>
                            </DialogTrigger>
                            <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
                                <DialogHeader>
                                    <DialogTitle>复制内容到平台发布</DialogTitle>
                                    <DialogDescription>
                                        选择目标平台，系统会自动适配格式，复制后粘贴到对应平台发布。
                                    </DialogDescription>
                                </DialogHeader>
                                <CopyToPlatform
                                    title={title}
                                    content={content.replace(/<[^>]*>/g, '')}
                                    tags={extractTags(content)}
                                />
                            </DialogContent>
                        </Dialog>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                    {/* 左侧 - 主编辑区 */}
                    <div className="lg:col-span-2 space-y-6">
                        {/* 标题输入 */}
                        <Card>
                            <CardContent className="pt-6">
                                <div className="space-y-4">
                                    <div className="flex gap-2">
                                        <Input
                                            placeholder="输入标题或选题..."
                                            className="text-lg font-medium"
                                            value={title}
                                            onChange={(e) => setTitle(e.target.value)}
                                        />
                                        <Button
                                            onClick={handleAIGenerate}
                                            disabled={isGenerating}
                                            className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600"
                                        >
                                            <Wand2 className={`h-4 w-4 mr-2 ${isGenerating ? 'animate-spin' : ''}`} />
                                            {isGenerating ? 'AI生成中...' : 'AI生成'}
                                        </Button>
                                    </div>

                                    {/* AI Tools Toolbar */}
                                    <div className="flex gap-2 p-2 bg-slate-50 dark:bg-slate-900/50 rounded-lg border">
                                        <div className="flex items-center gap-1 text-xs font-medium text-muted-foreground px-2">
                                            <Sparkles className="size-3" />
                                            AI 润色:
                                        </div>
                                        <Button
                                            variant="ghost" size="sm"
                                            className="h-7 text-xs gap-1 hover:text-violet-600 hover:bg-violet-50"
                                            onClick={handleAIPolish}
                                            disabled={isPolishing}
                                        >
                                            {isPolishing ? <Loader2 className="size-3 animate-spin" /> : <Wand2 className="size-3" />}
                                            {isPolishing ? '润色中...' : '一键美化'}
                                        </Button>
                                        <Button
                                            variant="ghost" size="sm"
                                            className="h-7 text-xs gap-1 hover:text-amber-600 hover:bg-amber-50"
                                            onClick={handleAILayout}
                                            disabled={isLayout}
                                        >
                                            {isLayout ? <Loader2 className="size-3 animate-spin" /> : <TrendingUp className="size-3" />}
                                            {isLayout ? '优化中...' : '智能排版'}
                                        </Button>
                                        <div className="w-px h-4 bg-border mx-1" />
                                        <Button
                                            variant="ghost" size="sm"
                                            className="h-7 text-xs gap-1 hover:text-blue-600 hover:bg-blue-50"
                                            onClick={() => toast.info('合规检测已内置在 AI 润色流程中')}
                                            disabled={isPolishing}
                                        >
                                            <Check className="size-3" />
                                            合规检测
                                        </Button>
                                    </div>
                                </div>
                            </CardContent>
                        </Card>

                        {/* 编辑区域标签页 */}
                        <Tabs value={activeTab} onValueChange={setActiveTab}>
                            <TabsList className="grid w-full grid-cols-3">
                                <TabsTrigger value="editor">
                                    <FileText className="h-4 w-4 mr-2" />
                                    内容编辑
                                </TabsTrigger>
                                <TabsTrigger value="media">
                                    <Video className="h-4 w-4 mr-2" />
                                    媒体上传
                                </TabsTrigger>
                                <TabsTrigger value="cover">
                                    <Image className="h-4 w-4 mr-2" />
                                    封面设计
                                </TabsTrigger>
                            </TabsList>

                            <TabsContent value="media" className="mt-4">
                                <Card>
                                    <CardHeader>
                                        <CardTitle className="text-lg">上传素材</CardTitle>
                                        <CardDescription>
                                            支持上传视频或图片，将自动同步到发布平台
                                        </CardDescription>
                                    </CardHeader>
                                    <CardContent>
                                        <FileUploader
                                            type={contentType === 'video' ? 'video' : 'image'}
                                            onUploadSuccess={(url) => {
                                                // 简单处理：将链接追加到内容底部，或者存入 mediaUrls (需后端支持)
                                                // 这里我们追加到编辑器内容里，模拟插入
                                                if (contentType === 'video') {
                                                    setContent(prev => prev + `<p><video src="${url}" controls width="100%"></video></p>`);
                                                } else {
                                                    setContent(prev => prev + `<p><img src="${url}" alt="Uploaded" /></p>`);
                                                }
                                                // 同时可以切换回编辑器tab查看
                                                setActiveTab('editor');
                                            }}
                                        />
                                    </CardContent>
                                </Card>
                            </TabsContent>

                            <TabsContent value="editor" className="mt-4">
                                <Card>
                                    <CardContent className="pt-6">
                                        <RichEditor
                                            content={content}
                                            onChange={setContent}
                                            placeholder="开始创作你的内容，或使用AI生成初稿..."
                                        />
                                    </CardContent>
                                </Card>
                            </TabsContent>

                            <TabsContent value="cover" className="mt-4">
                                <Card>
                                    <CardHeader>
                                        <CardTitle className="text-lg flex items-center gap-2">
                                            <Sparkles className="h-5 w-5 text-purple-500" />
                                            封面生成器
                                        </CardTitle>
                                        <CardDescription>
                                            选择模板并自定义封面内容，一键生成多平台封面图
                                        </CardDescription>
                                    </CardHeader>
                                    <CardContent>
                                        <PosterGenerator
                                            title={title || '输入你的标题'}
                                            subtitle="精心整理的超实用分享"
                                            author="创作者"
                                        />
                                    </CardContent>
                                </Card>
                            </TabsContent>
                        </Tabs>
                    </div>

                    {/* 右侧 - 设置面板 */}
                    <div className="space-y-6">
                        {/* 内容类型 */}
                        <Card>
                            <CardHeader className="pb-3">
                                <CardTitle className="text-base">内容类型</CardTitle>
                            </CardHeader>
                            <CardContent>
                                <div className="grid grid-cols-3 gap-2">
                                    {[
                                        { id: 'video', icon: Video, label: '视频' },
                                        { id: 'image', icon: Image, label: '图文' },
                                        { id: 'article', icon: FileText, label: '文章' },
                                    ].map(type => (
                                        <Button
                                            key={type.id}
                                            variant={contentType === type.id ? 'default' : 'outline'}
                                            className={`flex flex-col h-20 ${contentType === type.id ? 'bg-violet-600 hover:bg-violet-700' : ''}`}
                                            onClick={() => setContentType(type.id as any)}
                                        >
                                            <type.icon className="h-5 w-5 mb-1" />
                                            <span className="text-xs">{type.label}</span>
                                        </Button>
                                    ))}
                                </div>
                            </CardContent>
                        </Card>

                        {/* 发布平台 */}
                        <Card>
                            <CardHeader className="pb-3">
                                <CardTitle className="text-base">发布平台</CardTitle>
                                <CardDescription className="text-xs">选择要发布的平台</CardDescription>
                            </CardHeader>
                            <CardContent>
                                <div className="space-y-2">
                                    {platforms.map(platform => (
                                        <div
                                            key={platform.id}
                                            className={`flex items-center justify-between p-3 rounded-lg border cursor-pointer transition-all ${selectedPlatforms.includes(platform.id)
                                                ? 'border-violet-500 bg-violet-50 dark:bg-violet-950'
                                                : 'hover:bg-muted'
                                                }`}
                                            onClick={() => handlePlatformToggle(platform.id)}
                                        >
                                            <div className="flex items-center gap-3">
                                                <span className="text-xl">{platform.icon}</span>
                                                <span className="font-medium">{platform.name}</span>
                                            </div>
                                            {selectedPlatforms.includes(platform.id) && (
                                                <div className="h-5 w-5 rounded-full bg-violet-600 flex items-center justify-center">
                                                    <Check className="h-3 w-3 text-white" />
                                                </div>
                                            )}
                                        </div>
                                    ))}
                                </div>
                            </CardContent>
                        </Card>

                        {/* AI建议 */}
                        <Card className="bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-950 dark:to-pink-950 border-purple-200 dark:border-purple-800">
                            <CardHeader className="pb-3">
                                <CardTitle className="text-base flex items-center gap-2">
                                    <Sparkles className="h-4 w-4 text-purple-500" />
                                    AI建议
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="space-y-3">
                                <div className="text-sm space-y-2">
                                    <div className="flex items-start gap-2">
                                        <Badge variant="secondary" className="bg-purple-100 text-purple-700 mt-0.5">时间</Badge>
                                        <span className="text-muted-foreground">周六晚上8点发布效果最佳</span>
                                    </div>
                                    <div className="flex items-start gap-2">
                                        <Badge variant="secondary" className="bg-blue-100 text-blue-700 mt-0.5">标题</Badge>
                                        <span className="text-muted-foreground">建议使用数字和emoji增加吸引力</span>
                                    </div>
                                    <div className="flex items-start gap-2">
                                        <Badge variant="secondary" className="bg-green-100 text-green-700 mt-0.5">热点</Badge>
                                        <span className="text-muted-foreground">春节相关话题热度上升200%</span>
                                    </div>
                                </div>
                            </CardContent>
                        </Card>
                    </div>
                </div>
            </div>
        </DashboardLayout>
    );
}

export default function CreateContentPage() {
    return (
        <Suspense fallback={<div className="flex h-screen items-center justify-center"><Loader2 className="size-8 animate-spin text-muted-foreground" /></div>}>
            <CreateContentForm />
        </Suspense>
    );
}
